#
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#

name: Formatting

on:
  pull_request:
    branches: [master, main]

# on subsequent push cancel previously in progress jobs
concurrency:
  group: ${{ github.head_ref }}-prettier
  cancel-in-progress: true

jobs:
  prettier:
    # Doesn't run CI on draft PRs
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.X

      - name: Check formatting with prettier
        id: format
        run: npx prettier@2.7.1 --check ./src ./e2e
