name: Jest

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# on subsequent push cancel previously in progress jobs
concurrency:
  group: ${{ github.head_ref }}-test
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Run jest
        run: npm run test -- --watch=false --ci --silent --bail
